{%- set name = "diffpy.utils" -%}
{%- set version = "3.4.0rc10" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/33/32/0748b78a73ebe7987b2b00b28e3bd679c9cab855c79c68d5c17189d86145/diffpy_utilstestlee-3.2.0rc10.tar.gz
  sha256: 245f663152f96218a8ece5e61659963d0c1e333af5a136804f6fda73b3dbcb5b

build:
  noarch: python
  number: 3
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - setuptools
    - numpy >=1.3

test: 
  requires:
    - pip
    - pytest
    - pytest-mock
    - freezegun
  source_files:
    - tests/
  commands:
    - pip check
    - pytest tests/

about:
  home: https://github.com/diffpy/diffpy.utils/
  summary: Shared utilities for diffpy packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The diffpy.utils package provides functions for extracting array data from variously formatted text files and wx GUI utilities used by the PDFgui program. The package also includes an interpolation function based on the Whittaker-Shannon formula that can be used to resample a PDF or other profile function over a new grid.
  doc_url: http://diffpy.github.io/diffpy.utils/
  dev_url: https://github.com/diffpy/diffpy.utils/

extra:
  recipe-maintainers:
    - sbillinge
    - Sparks29032
    - dragonyanglong
    - CJ-Wright
    - pavoljuhas
